# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mailClient.ui'
#
# Created: Sun Aug  5 21:14:17 2012
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(509, 602)
        MainWindow.setMinimumSize(QtCore.QSize(509, 602))
        MainWindow.setMaximumSize(QtCore.QSize(509, 602))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.pushButtonCon = QtGui.QPushButton(self.centralwidget)
        self.pushButtonCon.setGeometry(QtCore.QRect(360, 10, 141, 31))
        self.pushButtonCon.setObjectName(_fromUtf8("pushButtonCon"))
        self.tabSpam = QtGui.QTabWidget(self.centralwidget)
        self.tabSpam.setGeometry(QtCore.QRect(10, 80, 491, 481))
        self.tabSpam.setObjectName(_fromUtf8("tabSpam"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.textBoxInbox = QtGui.QTextBrowser(self.tab)
        self.textBoxInbox.setGeometry(QtCore.QRect(70, 30, 411, 421))
        self.textBoxInbox.setObjectName(_fromUtf8("textBoxInbox"))
        self.pushButtonMarkAsSpam = QtGui.QPushButton(self.tab)
        self.pushButtonMarkAsSpam.setGeometry(QtCore.QRect(10, 0, 75, 30))
        self.pushButtonMarkAsSpam.setObjectName(_fromUtf8("pushButtonMarkAsSpam"))
        self.pushButtonPrevHam = QtGui.QPushButton(self.tab)
        self.pushButtonPrevHam.setGeometry(QtCore.QRect(320, 0, 75, 30))
        self.pushButtonPrevHam.setObjectName(_fromUtf8("pushButtonPrevHam"))
        self.pushButtonNextHam = QtGui.QPushButton(self.tab)
        self.pushButtonNextHam.setGeometry(QtCore.QRect(400, 0, 75, 30))
        self.pushButtonNextHam.setObjectName(_fromUtf8("pushButtonNextHam"))
        self.listWidgetInbox = QtGui.QListWidget(self.tab)
        self.listWidgetInbox.setGeometry(QtCore.QRect(0, 30, 71, 421))
        self.listWidgetInbox.setObjectName(_fromUtf8("listWidgetInbox"))
        self.tabSpam.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.textBoxSpam = QtGui.QTextBrowser(self.tab_2)
        self.textBoxSpam.setGeometry(QtCore.QRect(70, 30, 411, 421))
        self.textBoxSpam.setObjectName(_fromUtf8("textBoxSpam"))
        self.pushButtonNotSpam = QtGui.QPushButton(self.tab_2)
        self.pushButtonNotSpam.setGeometry(QtCore.QRect(10, 0, 75, 30))
        self.pushButtonNotSpam.setObjectName(_fromUtf8("pushButtonNotSpam"))
        self.pushButtonPrevSpam = QtGui.QPushButton(self.tab_2)
        self.pushButtonPrevSpam.setGeometry(QtCore.QRect(320, 0, 75, 30))
        self.pushButtonPrevSpam.setObjectName(_fromUtf8("pushButtonPrevSpam"))
        self.pushButtonNextSpam = QtGui.QPushButton(self.tab_2)
        self.pushButtonNextSpam.setGeometry(QtCore.QRect(400, 0, 75, 30))
        self.pushButtonNextSpam.setObjectName(_fromUtf8("pushButtonNextSpam"))
        self.listWidgetSpam = QtGui.QListWidget(self.tab_2)
        self.listWidgetSpam.setGeometry(QtCore.QRect(0, 30, 71, 421))
        self.listWidgetSpam.setObjectName(_fromUtf8("listWidgetSpam"))
        self.tabSpam.addTab(self.tab_2, _fromUtf8(""))
        self.lineEditServer = QtGui.QLineEdit(self.centralwidget)
        self.lineEditServer.setGeometry(QtCore.QRect(30, 40, 113, 20))
        self.lineEditServer.setObjectName(_fromUtf8("lineEditServer"))
        self.lineEditPassword = QtGui.QLineEdit(self.centralwidget)
        self.lineEditPassword.setGeometry(QtCore.QRect(220, 40, 113, 20))
        self.lineEditPassword.setText(_fromUtf8(""))
        self.lineEditPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditPassword.setPlaceholderText(_fromUtf8(""))
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.lineEditUsername = QtGui.QLineEdit(self.centralwidget)
        self.lineEditUsername.setGeometry(QtCore.QRect(220, 10, 113, 20))
        self.lineEditUsername.setObjectName(_fromUtf8("lineEditUsername"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 10, 51, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(160, 40, 51, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButtonDisconnect = QtGui.QPushButton(self.centralwidget)
        self.pushButtonDisconnect.setGeometry(QtCore.QRect(360, 50, 141, 31))
        self.pushButtonDisconnect.setObjectName(_fromUtf8("pushButtonDisconnect"))
        self.statusBar = QtGui.QLabel(self.centralwidget)
        self.statusBar.setGeometry(QtCore.QRect(190, 80, 81, 21))
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 509, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabSpam.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditServer, self.lineEditUsername)
        MainWindow.setTabOrder(self.lineEditUsername, self.lineEditPassword)
        MainWindow.setTabOrder(self.lineEditPassword, self.pushButtonCon)
        MainWindow.setTabOrder(self.pushButtonCon, self.tabSpam)
        MainWindow.setTabOrder(self.tabSpam, self.pushButtonNotSpam)
        MainWindow.setTabOrder(self.pushButtonNotSpam, self.textBoxSpam)
        MainWindow.setTabOrder(self.textBoxSpam, self.pushButtonPrevSpam)
        MainWindow.setTabOrder(self.pushButtonPrevSpam, self.pushButtonNextSpam)
        MainWindow.setTabOrder(self.pushButtonNextSpam, self.pushButtonNextHam)
        MainWindow.setTabOrder(self.pushButtonNextHam, self.pushButtonPrevHam)
        MainWindow.setTabOrder(self.pushButtonPrevHam, self.pushButtonMarkAsSpam)
        MainWindow.setTabOrder(self.pushButtonMarkAsSpam, self.textBoxInbox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Spam Filter v1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCon.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.textBoxInbox.setHtml(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonMarkAsSpam.setText(QtGui.QApplication.translate("MainWindow", "Report Spam", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrevHam.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNextHam.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSpam.setTabText(self.tabSpam.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Inbox", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNotSpam.setText(QtGui.QApplication.translate("MainWindow", "Not Spam", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonPrevSpam.setText(QtGui.QApplication.translate("MainWindow", "Previous", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonNextSpam.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.tabSpam.setTabText(self.tabSpam.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "Spam", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditServer.setText(QtGui.QApplication.translate("MainWindow", "imap.gmail.com", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditUsername.setText(QtGui.QApplication.translate("MainWindow", "", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Server:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Username:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Password:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDisconnect.setText(QtGui.QApplication.translate("MainWindow", "Disconnect", None, QtGui.QApplication.UnicodeUTF8))
        self.statusBar.setText(QtGui.QApplication.translate("MainWindow", "Not Connected", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbout.setTitle(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

